# Generated by Django 4.2.2 on 2023-08-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='deliveryman',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rentprovider',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='renttaker',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
